config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index, :show], constraints: { id: /[^\/]+/ } do
    resources :projects, only: [:index, :show], constraints: { id: /\S+/ } do
      get :bugs_by_team, to: redirect { |path_params, req| "/groups/#{path_params[:group_id]}/projects/#{path_params[:project_id]}/bugs_by_stage" }
      get :bugs_by_stage
      get :bugs_by_severity
      get :bugs_by_priority
      get :bugs_past_slo
      get :feature_proposals_by_team
      get :issues_by_state
      get :mrs_by_state
      get :regressions
      get :completed_deliverables_per_milestone
      get :missed_deliverables
      get :bug_classification
      get :developer_productivity_metrics, to: redirect { |path_params, req| "/groups/#{path_params[:group_id]}/projects/#{path_params[:project_id]}/average_mrs_per_milestone" }
      get :average_mrs_per_milestone
      get :throughputs
      get :average_mrs_per_month
      get :monthly_merged_mrs
      get :time_to_close_bugs
      resources :teams, only: [:show, :index], constraints: { id: /[^\/]+/ }
      resources :stages, only: [:show, :index]
      resources :sections, only: [:show]
    end

    get :bugs_by_team, to: redirect { |path_params, req| "/groups/#{path_params[:group_id]}/bugs_by_stage" }
    get :bugs_by_stage
    get :bugs_by_severity
    get :bugs_by_priority
    get :bugs_past_slo
    get :feature_proposals_by_team
    get :issues_by_state
    get :mrs_by_state
    get :regressions
    get :completed_deliverables_per_milestone
    get :missed_deliverables
    get :bug_classification
    get :developer_productivity_metrics, to: redirect { |path_params, req| "/groups/#{path_params[:group_id]}/average_mrs_per_milestone" }
    get :average_mrs_per_milestone
    get :throughputs
    get :average_mrs_per_month
    get :monthly_merged_mrs
    get :time_to_close_bugs
    resources :teams, only: [:show, :index]
    resources :stages, only: [:show, :index]
    resources :sections, only: [:show]
  end

  root 'groups#index'

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute", as: "graphql"
  post "/download/raw.:format", to: "raw_data#download", as: "download_raw_data"

end

app/models/concerns/issuable.rb
# frozen_string_literal: true

module Issuable
  THROUGHPUT_LABELS = %w[
    Community\ contribution
    security
    bug
    feature
    backstage
  ].freeze

  def milestone_title
    milestone&.dig('title')
  end

  def author_username
    author&.dig('username')
  end

  def project_full_path
    project.full_path
  end

  def url
    "https://gitlab.com/#{project_full_path}/#{self.class.name.underscore.pluralize}/#{iid}"
  end

  def throughput
    (THROUGHPUT_LABELS & labels).first
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :projects
  has_many :issues, through: :projects
  has_many :merge_requests, through: :projects

  has_many :revisions, through: :projects

  validates :path, uniqueness: true

  def full_path
    path
  end

  def latest_revision
    revisions.last
  end
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include Issuable

  belongs_to :project

  def age_in_days
    (Date.today - created_at).to_i
  end

  def age_in_months
    age_in_days / 30
  end

  def issuable_id
    issues_id
  end

  def merged_at
  end
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :project
end

app/models/merge_request.rb
class MergeRequest < ActiveRecord::Base
  include Issuable

  belongs_to :project

  def issuable_id
    merge_requests_id
  end

  def confidential
  end
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
end

app/models/pipeline.rb
class Pipeline < ActiveRecord::Base
  belongs_to :project
end

app/models/project.rb
class Project  < ActiveRecord::Base
  belongs_to :group
  has_many :revisions

  has_many :issues
  has_many :labels
  has_many :merge_requests
  has_many :milestones
  has_many :pipelines

  validates :path, uniqueness: true

  scope :listable, -> { where(dev: false) }

  def full_path
    "#{group.path}/#{path}"
  end

  def latest_revision
    revisions.last
  end

  def fetch_path
    override_path || full_path
  end
end

app/models/revision.rb
class Revision < ActiveRecord::Base
  belongs_to :project

  def to_s
    created_at.strftime('%d %B %Y %H:%M %Z')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = GitlabInsightsDashboardSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :find_group

  def index
    @groups = Group.all
  end

  def show
    @projects = @group.projects.listable
  end

  def find_group
    @group = Group.find_by(path: params[:group_id] || params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_group
  before_action :find_project, except: [:index]
  before_action :respond_404_for_dev_projects, except: [:index]

  def index
    @projects = @group.projects.listable
  end

  private

  def find_group
    @group = Group.find_by(path: params[:group_id])
  end

  def find_project
    @project = @group.projects.find_by(path: params[:project_id] || params[:id])
  end

  def respond_404_for_dev_projects
    not_found if @project && @project.dev?
  end
end

app/controllers/raw_data_controller.rb
# frozen_string_literal: true

require 'csv'

class RawDataController < ApplicationController
  protect_from_forgery with: :null_session

  def download
    respond_to do |format|
      format.csv do
        send_data csv_data, filename: "#{params[:name]}.csv"
      end
    end
  end

  private

  def csv_data
    issuables_raw_data =
      raw_data.dig('data', 'group', 'issuables_raw_data') ||
        raw_data.dig('data', 'project', 'issuables_raw_data')

    CSV.generate do |csv|
      csv << all_fields

      issuables_raw_data.each do |raw_data|
        csv << raw_data.values
      end
    end
  end

  def raw_data
    @raw_data ||= GitlabInsightsDashboardSchema.execute(query).to_h
  end

  def all_fields
    @all_fields ||= Types::IssuableType.fields.keys
  end

  def query
    params[:query].sub(
      # FIXME: We should not remove {} so greedily!
      /#{Regexp.escape(params[:name])}(.+?)\s*\{.+\}/,
      "issuables_raw_data\\1 { #{all_fields.join(', ')} } }}")
  end
end

app/controllers/sections_controller.rb
class SectionsController < StagesController
  def show
    super

    @team_for_link = @team.dup
    @team.gsub!('_', ' ')
  end
end

app/controllers/stages_controller.rb
class StagesController < ProjectsController
  before_action :find_project
  before_action :respond_404_for_dev_projects

  def show
    @source = @project || @group
    @team = params[:id]
  end
end

app/controllers/teams_controller.rb
class TeamsController < ProjectsController
  before_action :find_project
  before_action :respond_404_for_dev_projects

  def show
    @source = @project || @group
    @team = params[:id].titleize.sub('Deprecated', 'DEPRECATED')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def last_updated_string
    source = @project ? @project : @group
    "Last updated: #{source.latest_revision}" if source
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/groups/average_mrs_per_milestone.haml
= render partial: 'shared/average_mrs_per_milestone', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'average mrs merged per author per milestone', link: method(:group_project_average_mrs_per_milestone_path) }

app/views/groups/average_mrs_per_month.haml
= render partial: 'shared/average_mrs_per_month', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'average mrs merged per author per month', link: method(:group_project_average_mrs_per_month_path) }

app/views/groups/bug_classification.html.haml
= render partial: 'shared/bug_classification', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bug classification', link: method(:group_project_bug_classification_path) }

app/views/groups/bugs_by_priority.html.haml
= render partial: 'shared/bugs_by_priority', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs by priority', link: method(:group_project_bugs_by_priority_path) }

app/views/groups/bugs_by_severity.html.haml
= render partial: 'shared/bugs_by_severity', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs by severity', link: method(:group_project_bugs_by_severity_path) }

app/views/groups/bugs_by_stage.html.haml
= render partial: 'shared/bugs_by_stage', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs by stage', link: method(:group_project_bugs_by_stage_path) }

app/views/groups/bugs_past_slo.html.haml
= render partial: 'shared/bugs_past_slo', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'bugs past slo', link: method(:group_project_bugs_past_slo_path) }

app/views/groups/feature_proposals_by_team.html.haml
= render partial: 'shared/feature_proposals_by_team', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'feature proposals by team', link: method(:group_project_feature_proposals_by_team_path) }

app/views/groups/index.html.haml
.container
  .page-header
    %h1.page-title Available Groups
  .row
    .list-group
      - @groups.each do |group|
        = link_to group.path, group_path(group.path), class: 'list-group-item'

app/views/groups/missed_deliverables.html.haml
= render partial: 'shared/missed_deliverables', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'missed deliverables', link: method(:group_project_missed_deliverables_path) }

app/views/groups/monthly_merged_mrs.html.haml
= render partial: 'shared/monthly_merged_mrs', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'monthly_merged_mrs', link: method(:group_project_monthly_merged_mrs_path) }

app/views/groups/mrs_by_state.html.haml
= render partial: 'shared/mrs_by_state', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'merge requests by state', link: method(:group_project_mrs_by_state_path) }

app/views/groups/show.html.haml
.container
  .page-header
    %h1.page-title
      %strong= "`#{@group.path}` group dashboards"

  .row
    .col-md-6.col-lg-4
      %h3.page-title Top-level dashboards
      .list-group
        = link_to 'Monthly Merged MRs', group_monthly_merged_mrs_path(@group.path), class: 'list-group-item'
        = link_to 'Merge Request Throughputs', group_throughputs_path(@group.path), class: 'list-group-item'
        = link_to 'Average MRs Merged Per Author Per Month', group_average_mrs_per_month_path(@group.path), class: 'list-group-item'
        = link_to 'Bugs By Stage', group_bugs_by_stage_path(@group.path), class: 'list-group-item'
        = link_to 'Bugs By Severity', group_bugs_by_severity_path(@group.path), class: 'list-group-item'
        = link_to 'Bugs By Priority', group_bugs_by_priority_path(@group.path), class: 'list-group-item'
        = link_to 'Bug Classification', group_bug_classification_path(@group.path), class: 'list-group-item'
        = link_to 'Bugs Past SLO', group_bugs_past_slo_path(@group.path), class: 'list-group-item'
        = link_to 'Time to Close Bugs', group_time_to_close_bugs_path(@group.path), class: 'list-group-item'
        = link_to 'Feature Proposals by Team', group_feature_proposals_by_team_path(@group.path), class: 'list-group-item'
        = link_to 'Issues by State', group_issues_by_state_path(@group.path), class: 'list-group-item'
        = link_to 'EXPERIMENTAL - Merge Requests by State', group_mrs_by_state_path(@group.path), class: 'list-group-item'
        = link_to 'EXPERIMENTAL - Completed Deliverables vs non-Deliverables Per Milestone', group_completed_deliverables_per_milestone_path(@group.path), class: 'list-group-item'
        = link_to 'Regressions [MIGRATED]', group_regressions_path(@group.path), class: 'list-group-item'
        = link_to 'Missed Deliverables [MIGRATED]', group_missed_deliverables_path(@group.path), class: 'list-group-item'
        = link_to 'Average MRs Merged Per Author Per Milestone [Deprecated]', group_average_mrs_per_milestone_path(@group.path), class: 'list-group-item'

    .col-md-6.col-lg-4
      %h3.page-title Stage/Group & Team dashboards
      .list-group
        = link_to 'View dashboards for DevOps stages & groups', group_stages_path(@group.path), class: 'list-group-item'
        = link_to 'View dashboards for teams', group_teams_path(@group.path), class: 'list-group-item'

      %h3.page-title Project dashboards
      .list-group= link_to 'View the project dashboards', group_projects_path(@group.path), class: 'list-group-item'

app/views/groups/time_to_close_bugs.html.haml
= render partial: 'shared/time_to_close_bugs', locals: { source: @group }
= render partial: 'shared/project_level_links', locals: { group: @group, name: 'time to close bugs', link: method(:group_project_time_to_close_bugs_path) }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GitLab Quality Dashboard
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .header.py-4
      .container
        .row.align-items-center
          .col-lg-1.order-lg-first
            = link_to 'Insights', groups_path, class: 'header-brand'
          .col-lg
            = render 'notices/deprecation_notice'
    .header.collapse.d-lg-flex.p-0
      .container
        .row.align-items-center
          .col-lg-3.ml-auto
            %div
              = last_updated_string
          .col-lg.order-lg-first
            %ul.nav.nav-tabs.border-0.flex-column.flex-lg-row
              %li.nav-item
                = link_to 'Groups', groups_path, class: 'nav-link'
              - if @group
                %li.nav-item >
                %li.nav-item
                  = link_to @group.path, group_path(@group.path), class: 'nav-link'
              - if @project
                %li.nav-item >
                %li.nav-item
                  = link_to 'Projects', group_projects_path(@group.path), class: 'nav-link'
                %li.nav-item >
                %li.nav-item
                  = link_to @project.path, group_project_path(@group.path, @project.path), class: 'nav-link'
    .page
      .page-main
        .my-3.my-md-5
          - if @group && !@project
            = hidden_field_tag "group_path", @group.path, { :id=> "group-path" }
          - if @project
            = hidden_field_tag "group_path", @project.group.path, { :id=> "group-path" }
            = hidden_field_tag "project_path", @project.path, { :id=> "project-path" }
          = hidden_field_tag "download_csv_path", download_raw_data_path(format: 'csv'), { :id=> "download-csv-path" }
          = yield

app/views/notices/_deprecation_notice.html.haml
.alert.alert-primary.alert-icon
  %i.fe.fe-bell.mr-2{ aria: { hidden: true } }
  .notice
    = succeed '.' do
      The Quality dashboard will be deprecated in favour of
      = link_to 'Periscope', 'https://about.gitlab.com/handbook/business-ops/data-team/periscope-directory/'
      and
      = link_to 'GitLab Insights', 'https://docs.gitlab.com/ee/user/project/insights/index.html'
    = succeed '.' do
      For more info please see the
      = link_to 'deprecation plan', 'https://gitlab.com/gitlab-org/gitlab-insights/issues/116'

app/views/projects/average_mrs_per_milestone.haml
= render partial: 'shared/average_mrs_per_milestone', locals: { source: @project }

app/views/projects/average_mrs_per_month.haml
= render partial: 'shared/average_mrs_per_month', locals: { source: @project }

app/views/projects/bug_classification.html.haml
= render partial: 'shared/bug_classification', locals: { source: @project }

app/views/projects/bugs_by_severity.html.haml
= render partial: 'shared/bugs_by_severity', locals: { source: @project }

app/views/projects/bugs_by_stage.html.haml
= render partial: 'shared/bugs_by_stage', locals: { source: @project }

app/views/projects/bugs_past_slo.html.haml
= render partial: 'shared/bugs_past_slo', locals: { source: @project }

app/views/projects/feature_proposals_by_team.html.haml
= render partial: 'shared/feature_proposals_by_team', locals: { source: @project }

app/views/projects/index.html.haml
.container
  .page-header
    %h1.page-title= "Group Dashboard: #{@group.path} projects"
  .row
    .col-md-6.col-lg-4
      %h3.page-title Available Projects
      .list-group
        - @projects.each do |project|
          = link_to project.path, group_project_path(@group.path, project.path), class: 'list-group-item'

app/views/projects/issues_by_state.html.haml
= render partial: 'shared/issues_by_state', locals: { source: @project }

app/views/projects/monthly_merged_mrs.html.haml
= render partial: 'shared/monthly_merged_mrs', locals: { source: @project }

app/views/projects/mrs_by_state.html.haml
= render partial: 'shared/mrs_by_state', locals: { source: @project }

app/views/projects/regressions.html.haml
= render partial: 'shared/regressions', locals: { source: @project }

app/views/projects/show.html.haml
.container
  .page-header
    %h1.page-title
      %strong= "`#{@group.path}/#{@project.path}` project dashboards"

  .row
    .col-md-6.col-lg-4
      %h3.page-title Top-level dashboards
      .list-group
        = link_to 'Monthly Merged MRs', group_project_monthly_merged_mrs_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Merge Request Throughputs', group_project_throughputs_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Average MRs Merged Per Author Per Month', group_project_average_mrs_per_month_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bugs By Stage', group_project_bugs_by_stage_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bugs By Severity', group_project_bugs_by_severity_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bugs By Priority', group_project_bugs_by_priority_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bug Classification', group_project_bug_classification_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Bugs Past SLO', group_project_bugs_past_slo_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Time to Close Bugs', group_project_time_to_close_bugs_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Feature Proposals by Team', group_project_feature_proposals_by_team_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Issues by State', group_project_issues_by_state_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'EXPERIMENTAL - Merge Requests by State', group_project_mrs_by_state_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'EXPERIMENTAL - Completed Deliverables vs non-Deliverables Per Milestone', group_project_completed_deliverables_per_milestone_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Regressions [MIGRATED]', group_project_regressions_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Missed Deliverables [MIGRATED]', group_project_missed_deliverables_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'Average MRs Merged Per Author Per Milestone [Deprecated]', group_project_average_mrs_per_milestone_path(@group.path, @project.path), class: 'list-group-item'

    .col-md-6.col-lg-4
      %h3.page-title Stage/Group & Team dashboards
      .list-group
        = link_to 'View dashboards for DevOps stages & groups', group_project_stages_path(@group.path, @project.path), class: 'list-group-item'
        = link_to 'View dashboards for teams', group_project_teams_path(@group.path, @project.path), class: 'list-group-item'

app/views/projects/time_to_close_bugs.html.haml
= render partial: 'shared/time_to_close_bugs', locals: { source: @project }

app/views/sections/show.html.haml
= render partial: 'shared/department_dashboard', locals: { source: @source, team: @team, view_name: 'section', group_project_path: :group_project_section_path }

app/views/shared/_average_mrs_per_milestone.haml
.container
  .page-header
    %h1.page-title= "Dashboard: #{source.path}"
  .page-header
    %h2.page-title Deprecated - Average MRs Merged Per Author Per Milestone Charts
  %p
    Note: Bars in
    %span{ style: "background-color: #{GitlabInsights::COLOR_SCHEME[:apricot]}" }= GitlabInsights::COLOR_SCHEME[:apricot]
    are in progress, i.e. that the milestone is still active.
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Deprecated - Average MRs Merged Per Author Per Milestone (GitLab only, excluding Community Contributions)
        .card-body
          %canvas#average-mrs-milestone-team
        .card-body
          %div
            %div.text-wrap
              %p Chart to display the average number of merge requests per author that have been merged in a milestone. Only MRs without the `Community contribution` label will be considered.
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Deprecated - Average MRs Merged Per Author Per Milestone (Including Community Contributions)
        .card-body
          %canvas#average-mrs-milestone-all
        .card-body
          %div
            %div.text-wrap
              %p Chart to display the average number of merge requests per author that have been merged in a milestone.

app/views/shared/_department_dashboard.html.haml
- if @source
  = hidden_field_tag "team_label", @team, { :id=> "team-label" }

.container
  .page-header
    %h1.page-title
      %strong= "Team dashboard for `#{@source.path}`: #{@team}"
  .row.row-cards
    .col-6.col-sm-4.col-lg-2
      .card
        .card-body.p-3.text-center
          #team-bugs-severity-number
            .total.h1.m-0 0
          .text-muted.mb-4 Percentage Open Bugs Severitized
    .col-6.col-sm-4.col-lg-2
      .card
        .card-body.p-3.text-center
          #team-bugs-priority-number
            .total.h1.m-0 0
          .text-muted.mb-4 Percentage Open Bugs Prioritized
    .col-4
      .card
        .card-header
          %h3.card-title Open Bugs by Severity
        %canvas#team-bugs-severity-pie
    .col-4
      .card
        .card-header
          %h3.card-title Open Bugs by Priority
        %canvas#team-bugs-priority-pie
  .row.row-cards
    .col-lg-6
      .card
        .card-header
          %h3.card-title Completed Deliverables vs non-Deliverables Per Milestone
        .card-body
          %canvas#team-completed-deliverables-per-milestone
        .card-body
          %div
            %div.text-wrap
              %p Displays number of closed issues with vs without the `Deliverable` and `#{@team}` label grouped by their milestone
    .col-lg-6
      .card
        .card-header
          %h3.card-title Missed Deliverables Per Milestone
        .card-body
          %canvas#team-missed-deliverables-per-milestone
        .card-body
          %div
            %div.text-wrap
              %p Displays number of open issues with the `missed-deliverable` and `#{@team}` label grouped by their `missed:milestone` label
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Regressions Per Milestone
        .card-body
          %canvas#team-regressions-per-milestone
        .card-body
          %div
            %div.text-wrap
              %p Displays number of open issues with the `regression` and `#{@team}` label grouped by their `regression:milestone` label
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Weekly Throughput
        .card-body
          %canvas#team-mrs-per-week
        .card-body
          %div
            %div.text-wrap
              %p Displays number of merged MRs per week for the `#{@team}` team grouped by MR categories. These MRs could have been merged to any branch, not only `master`. The date used to place in a period is the date that the MR was actually merged. At the weekly level, we go back 12 weeks (1 quarter period).
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Monthly Throughput
        .card-body
          %canvas#team-mrs-per-month
        .card-body
          %div
            %div.text-wrap
              %p Displays number of merged MRs per month for the `#{@team}` team grouped by MR categories. These MRs could have been merged to any branch, not only `master`. The date used to place in a period is the date that the MR was actually merged. At the monthly level, we go back 24 months (2 year period)
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Cumulative open bugs by priority
        .card-body
          %canvas#cumulative-bugs-created-priority-month-team
        .card-body
          %div
            %div.text-wrap
              %p Displays number of open bugs created over time grouped by their priority label for the `#{@team}` label
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Open bugs by create month/priority
        .card-body
          %canvas#bugs-created-per-month-bar
        .card-body
          %div
            %div.text-wrap
              %p Displays number of open bugs created in a particular month for the `#{@team}` label
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Closed bugs by month/priority
        .card-body
          %canvas#bugs-closed-per-month-bar
        .card-body
          %div
            %div.text-wrap
              %p Displays number of closed bugs closed in a particular month for the `#{@team}` label
  .row.row-cards
    .col-lg-12
      .card
        .card-header
          %h3.card-title Bugs Opened vs Closed Per Month
        .card-body
          %canvas#bugs-opened-closed-month-team
        .card-body
          %div
            %div.text-wrap
              %p Displays number of bugs opened and closed each month for the `#{@team}` label

- puts @team_for_link
- if @source.is_a? Group
  = render partial: 'shared/project_level_links', locals: { group: @group, name: view_name, link: method(group_project_path), id: @team_for_link || @team }

app/views/stages/_stages_and_groups.html.haml
- section = local_assigns.fetch(:section)
- group = local_assigns.fetch(:group)
- project = local_assigns.fetch(:project, nil)

- section.each do |stage, devops_groups|
  - if project
    = link_to(stage, group_project_stage_path(group.path, project.path, stage), class: 'page-title')
    .list-group
      - devops_groups.each do |devops_group|
        %li.list-group-item= link_to(devops_group, group_project_section_path(group.path, project.path, devops_group.gsub(' ', '_')))
  - else
    = link_to(stage, group_stage_path(group.path, stage), class: 'page-title')
    .list-group
      - devops_groups.each do |devops_group|
        %li.list-group-item= link_to(devops_group, group_section_path(group.path, devops_group.gsub(' ', '_')))

app/views/stages/show.html.haml
= render partial: 'shared/department_dashboard', locals: { source: @source, team: @team, view_name: 'stage', group_project_path: :group_project_stage_path }